### ISSUE TITLE
vue-cal doesn't work at all

### ISSUE THREAD

**Issue by guynikan** [antoniandre/vue-cal-v4#474]
I have that exactly config present in codesandbox in my machine too, but only works in codesandbox, see here:
https://codesandbox.io/s/clever-buck-79x3y0?file=/src/App.vue

In my machine the error is: 

_Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (vuecal.common.js?7fa7:6542:1)
    at eval (vuecal.common.js?7fa7:7684:1)
    at eval (vuecal.common.js?7fa7:11650:1)
    at eval (vuecal.common.js?7fa7:11652:1)
    at Object../node_modules/vue-cal/dist/vuecal.common.js (app.js:1127:1)
    at __webpack_require__ (app.js:790:30)
    at fn (app.js:101:20)
    at eval (main.js?56d7:1:1)
    at Module../src/main.js (app.js:1549:1)
    at __webpack_require__ (app.js:790:30)_

Anyone have any idea why, please?

If you need more info, please let me know.

(sorry about my horrible english, I'm try to improve it).

**Comment by Tyler-RCSD** [comment]
I have the same problem with 3.10.3.  I downgraded to 3.10.1 and it works.

**Comment by antoniandre** [comment]
Hi @guynikan, (@Duncank, @leandrocooper, @Tyler-RCSD)
Thanks for reporting.
This is now fixed in the version 3.10.4.

Make sure you use the latest Vue 2 as well `npm i vue@2.6.14 vue-template-compiler@2.6.14`.

**Comment by rubjo** [comment]
@antoniandre ...is there a chance vue-cal@next is also broken by a recent publish or something?

https://stackblitz.com/edit/vue3-script-setup-with-vite-qcskuh?file=src%2FApp.vue

Edit: never mind, crashes with Vite 2.9.4 for some reason, works again with 2.9.5...
